#!/usr/bin/env python3
"""Freeze branch-tracked upstream projects to observed immutable SHAs.

Deterministic generation step for diamaneos.xml (manifest integration follow-up):
reads default.xml (byte-identical upstream preservation) plus
upstream-pins-<date>.json (observed HEAD SHAs) and emits remove-project +
pinned re-add elements for the 125 branch-tracked forks. The 932 AOSP
projects keep inheriting the immutable release tag from <default> and are
never rewritten.

Usage: python3 freeze.py  (run from WORK_ROOT/manifest)
Validates: every effective project revision immutable (40-hex or refs/tags/*),
no duplicate checkout paths.
"""
import json
import os
import re
import sys
import xml.dom.minidom

HERE = os.path.dirname(os.path.abspath(__file__))
SHA_RE = re.compile(r"^[0-9a-f]{40}$")


def main():
    pins_path = os.path.join(HERE, "upstream-pins-2026-09-10.json")
    pins = json.load(open(pins_path))["projects"]
    doc = xml.dom.minidom.parse(os.path.join(HERE, "default.xml"))
    by_name = {}
    for p in doc.getElementsByTagName("project"):
        by_name[p.getAttribute("name")] = (
            p.getAttribute("path") or p.getAttribute("name"),
            p.getAttribute("remote"))
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- diamaneos.xml: GENERATED by freeze.py — do not hand-edit. -->",
        "<!-- Pins the 125 branch-tracked upstream forks to observed SHAs. -->",
        "<manifest>",
        '  <remote name="diamaneos"',
        '          fetch="https://codeberg.org/DiamaneOS/" />',
    ]
    for name in sorted(pins):
        if name not in by_name:
            print(f"WARNING: pinned {name} not in default.xml; skipped",
                  file=sys.stderr)
            continue
        path, remote = by_name[name]
        sha = pins[name]["head_sha"]
        lines.append(f'  <remove-project name="{name}" />')
        # Same upstream remote, immutable revision: the result syncs today.
        # Downstream fork migration (device source inventory / FP6 product integration) changes remote with review.
        lines.append(f'  <project name="{name}" path="{path}" '
                     f'remote="{remote}" revision="{sha}" />')
    lines.append("</manifest>")
    # NOTE: the diamaneos remote entry is reserved for downstream forks
    # (device source inventory / FP6 product integration); this generated delta only overrides revisions.
    # Validation runs against upstream remotes:
    errors = []
    seen_paths = {}
    for p in doc.getElementsByTagName("project"):
        name = p.getAttribute("name")
        path = p.getAttribute("path") or name
        seen_paths.setdefault(path, []).append(("default.xml", name))
    for name in sorted(pins):
        if name not in by_name:
            continue
        path, _remote = by_name[name]
        seen_paths.setdefault(path, []).append(("diamaneos.xml", name))
        sha = pins[name]["head_sha"]
        if not SHA_RE.match(sha):
            errors.append(f"non-immutable pin for {name}: {sha}")
    for path, owners in sorted(seen_paths.items()):
        if len(owners) > 1 and not any(o[0] == "diamaneos.xml" for o in owners):
            errors.append(f"duplicate path {path}: {owners}")
    # default tag check
    for d in doc.getElementsByTagName("default"):
        rev = d.getAttribute("revision")
        if not (SHA_RE.match(rev) or rev.startswith("refs/tags/")):
            errors.append(f"floating default revision: {rev}")
    # remote revisions must not float either
    for r in doc.getElementsByTagName("remote"):
        rev = r.getAttribute("revision")
        if rev and not (SHA_RE.match(rev) or rev.startswith("refs/tags/")):
            print(f"NOTE: floating remote revision overridden by delta: "
                  f"{r.getAttribute('name')}={rev}", file=sys.stderr)
    if errors:
        print("VALIDATION FAILED:", file=sys.stderr)
        for e in errors:
            print(" -", e, file=sys.stderr)
        return 1
    with open(os.path.join(HERE, "diamaneos.xml"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"diamaneos.xml written: {len(pins)} pinned overrides; "
          f"{len(seen_paths)} effective paths, no duplicates.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
