#!/usr/bin/env python3
"""Freeze branch-tracked upstream projects to observed immutable SHAs.

Deterministic generation step for diamaneos.xml (manifest integration follow-up):
reads default.xml (byte-identical upstream preservation) plus
upstream-pins-<date>.json (observed HEAD SHAs) and emits <extend-project>
revision overrides for the 125 branch-tracked forks. extend-project changes
ONLY the revision: linkfile/groups/clone-depth/aosp-name definitions stay
exactly as upstream published them. The 932 AOSP projects keep inheriting
the immutable release tag from <default> and are never rewritten.

Usage:
  python3 freeze.py            regenerate diamaneos.xml + validate
  python3 freeze.py --check    validate current files, write nothing
  python3 freeze.py --self-test
      built-in negative probes on temp copies (unpinned add must fail,
      path collision must fail); exit non-zero on any miss.

Validates: every effective project revision immutable (40-hex or
refs/tags/*), no duplicate checkout paths.
"""
import json
import os
import re
import shutil
import sys
import tempfile
import xml.dom.minidom

HERE = os.path.dirname(os.path.abspath(__file__))
SHA_RE = re.compile(r"^[0-9a-f]{40}$")


def load(here=HERE):
    pins = json.load(open(os.path.join(
        here, "upstream-pins-2026-09-10.json")))["projects"]
    doc = xml.dom.minidom.parse(os.path.join(here, "default.xml"))
    return pins, doc


def generate(pins, doc):
    by_name = {}
    for p in doc.getElementsByTagName("project"):
        by_name[p.getAttribute("name")] = p
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- diamaneos.xml: GENERATED by freeze.py — do not hand-edit. -->",
        "<!-- Revision-only overrides; all other project definitions stay upstream. -->",
        "<manifest>",
        '  <remote name="diamaneos"',
        '          fetch="https://codeberg.org/DiamaneOS/" />',
    ]
    skipped = []
    for name in sorted(pins):
        if name not in by_name:
            skipped.append(name)
            continue
        lines.append(f'  <extend-project name="{name}" '
                     f'revision="{pins[name]["head_sha"]}" />')
    lines.append("</manifest>")
    return lines, skipped


def effective_table(doc, delta_doc):
    """Apply remove-project/extend-project/new projects over default.xml."""
    table = {}
    for p in doc.getElementsByTagName("project"):
        name = p.getAttribute("name")
        table[name] = {
            "path": p.getAttribute("path") or name,
            "revision": (p.getAttribute("revision") or None),
            "remote": p.getAttribute("remote") or None,
            "origin": "default.xml",
        }
    default_rev = doc.getElementsByTagName("default")[0].getAttribute(
        "revision")
    remotes = {r.getAttribute("name"): r.getAttribute("revision")
               for r in doc.getElementsByTagName("remote")}
    for r in delta_doc.getElementsByTagName("remove-project"):
        table.pop(r.getAttribute("name"), None)
    for p in delta_doc.getElementsByTagName("extend-project"):
        name = p.getAttribute("name")
        if name in table and p.getAttribute("revision"):
            table[name]["revision"] = p.getAttribute("revision")
            table[name]["origin"] += "+diamaneos.xml"
    for p in delta_doc.getElementsByTagName("project"):
        name = p.getAttribute("name")
        table[name] = {
            "path": p.getAttribute("path") or name,
            "revision": p.getAttribute("revision") or None,
            "remote": p.getAttribute("remote") or None,
            "origin": "diamaneos.xml",
        }
    # Resolve empty revisions through remote, then manifest default.
    for name, row in table.items():
        if not row["revision"]:
            row["revision"] = (remotes.get(row["remote"] or "") or
                               default_rev)
            row["origin"] += " (inherited)"
    return table


def validate(table):
    errors = []
    paths = {}
    for name, row in sorted(table.items()):
        rev = row["revision"] or ""
        if not (SHA_RE.match(rev) or rev.startswith("refs/tags/")):
            errors.append(f"floating revision: {name}={rev or '(empty)'}")
        paths.setdefault(row["path"], []).append(name)
    for path, names in sorted(paths.items()):
        if len(names) > 1:
            errors.append(f"duplicate path {path}: {names}")
    return errors


def check(here=HERE, delta_name="diamaneos.xml"):
    pins, doc = load(here)
    delta_doc = xml.dom.minidom.parse(os.path.join(here, delta_name))
    table = effective_table(doc, delta_doc)
    return table, validate(table)


def self_test():
    failures = []
    # Probe 1: an added project inheriting the moving branch must fail.
    tmp = tempfile.mkdtemp(prefix="freeze-probe-")
    for f in ("default.xml", "upstream-pins-2026-09-10.json"):
        shutil.copy(os.path.join(HERE, f), tmp)
    pins, doc = load(HERE)
    lines, _ = generate(pins, doc)
    lines.insert(-1, '  <project name="probe-unpinned" path="probe/unpinned" '
                     'remote="grapheneos" />')
    open(os.path.join(tmp, "diamaneos.xml"), "w").write("\n".join(lines)
                                                        + "\n")
    _, errors = check(tmp)
    if not any("probe-unpinned" in e and "floating" in e for e in errors):
        failures.append("unpinned added project was accepted")
    # Probe 2: a genuine path collision must fail.
    lines2, _ = generate(pins, doc)
    lines2.insert(-1, '  <project name="probe-collision" path="build/make" '
                      'remote="grapheneos" revision="refs/tags/android-17.0.0_r1" />')
    open(os.path.join(tmp, "diamaneos.xml"), "w").write("\n".join(lines2)
                                                        + "\n")
    _, errors2 = check(tmp)
    if not any("build/make" in e and "duplicate" in e for e in errors2):
        failures.append("path collision was accepted")
    shutil.rmtree(tmp, ignore_errors=True)
    if failures:
        for f in failures:
            print("SELF-TEST FAIL:", f, file=sys.stderr)
        return 1
    print("self-test: unpinned add rejected, collision rejected.")
    return 0


def main(argv):
    if "--self-test" in argv:
        return self_test()
    pins, doc = load()
    lines, skipped = generate(pins, doc)
    for name in skipped:
        print(f"WARNING: pinned {name} not in default.xml; skipped",
              file=sys.stderr)
    if "--check" not in argv:
        with open(os.path.join(HERE, "diamaneos.xml"), "w") as fh:
            fh.write("\n".join(lines) + "\n")
    delta_doc = xml.dom.minidom.parse(os.path.join(HERE, "diamaneos.xml"))
    table = effective_table(doc, delta_doc)
    errors = validate(table)
    if errors:
        print("VALIDATION FAILED:", file=sys.stderr)
        for e in errors[:20]:
            print(" -", e, file=sys.stderr)
        return 1
    floating = sum(1 for r in table.values()
                   if not (SHA_RE.match(r["revision"] or "")
                           or (r["revision"] or "").startswith("refs/tags/")))
    print(f"effective manifest: {len(table)} projects, {floating} floating, "
          f"paths unique.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
